spring:
  datasource:
    url: jdbc:mysql://server1.inuappcenter.kr/heeyoung_app
    username: heeyoung
    password: Heeyoung123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

jwt:
  secret: aldjf2@#$239klasd@#$*@#Lrfkla@#23
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

