name: heeyoung

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 빌드 후 도커 허브에 푸쉬
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 버전 설정
        uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: application-prod.yml 환경변수 주입
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          spring.datasource.url: ${{secrets.MYSQL_URL}}
          spring.datasource.name: ${{secrets.MYSQL_USERNAME}}
          spring.datasource.password: ${{secrets.MYSQL_PASSWORD}}
          jwt.secret: ${{secrets.JWT_SECRET}}

      - name: JAR 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test -i --no-daemon -Ospring.profiles.active=prod

      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: 도커 이미지 빌드
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/heeyoung-server:latest .

      - name: 도커 이미지 푸쉬
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/heeyoung-server:latest

  deploy:
    name: 앱센터 서버에 배포
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/cheoukout@v3

      - name: docker-compose, logstash 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          source: "docker-compose.yml"
          target: "/home/serverking/17-basic-server/heeyoung"

      - name: 앱센터 서버에 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          script: |
            cd /home/serverking/heeyoung

            echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env

            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker image prune -f